name: Pull Request Target POC
on: 
  pull_request_target:
    types:
      - opened

jobs:
  print-variables:
    name: Print Variables
    runs-on: ubuntu-latest
    steps:
      - run: 'echo {secrets.TEST_VARIABLE}'

