name: Pull Request Target POC
on: 
  pull_request:
    types:
      - opened

jobs:
  print-variables:
    name: Print Variables
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Print TEST_VARIABLE from target branch
        shell: bash
        run: |
          echo ${{vars.TEST_VARIABLE}}
          echo '${{vars.TEST_VARIABLE}}'
          echo Hello?

