name: Pull Request Target POC
on: 
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  determine-environment:
    name: Determine the target environment
    runs-on: ubuntu-latest
    outputs: 
      target_environment: ${{steps.get-environment.outputs.ENVIRONMENT}}
    steps:
      - name: What branch are we merging into?
        shell: bash
        id: get-environment
        run: |
          TARGET_BRANCH=github.event.pull_request.base.ref
          ENVIRONMENT=''

          
          if [ "$TARGET_BRANCH" = "main" ]; then
            ENVIRONMENT='prod'
          fi

          echo "Target environment is: $ENVIRONMENT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_OUTPUT"
          

  print-variables-prod:
    # environment: ${{ steps.get-environment.outputs.ENVIRONMENT}} # need to figure out how to determine this dynamically
    if: github.event.pull_request.base.ref == 'main'
    environment: 'prod'
    name: Print Variables
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_VARIABLE: ${{ vars.TEST_VARIABLE}}
      # ENVIRONMENT: ${{ step.get-environment.outputs.ENVIRONMENT}} # need to figure out how to determine this dynamically
    steps:
      - name: Print TEST_VARIABLE from target branch
        shell: bash
        run: |
          echo "TEST_VARIABLE: $TEST_VARIABLE"

  print-variables-dynamic:
    needs: determine-environment
    environment: 
      name: ${{needs.determine-environment.outputs.target_environment}}
    name: Print Variables With Dynamic Environment
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_VARIABLE: ${{ vars.TEST_VARIABLE}}
    steps:
      - name: Print TEST_VARIABLE from target branch
        shell: bash
        run: |
          echo "TEST_VARIABLE: $TEST_VARIABLE"
