name: Pull Request Target POC
on:
  push:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  # This whole job can be replaced with: https://github.com/q4mobile/events-platform/blob/develop/.github/workflows/build.yml
  determine-environment:
    name: Determine the target environment
    runs-on: ubuntu-latest
    outputs:
      target_environment: ${{steps.get-environment.outputs.ENVIRONMENT}}
    steps:
      - name: What branch are we merging into?
        id: get-environment
        shell: bash
        run: |
          TARGET_BRANCH=${{github.event.pull_request.base.ref}}
          ENVIRONMENT=''

          if [ "$TARGET_BRANCH" = "main" ]; then
            ENVIRONMENT='prod'
          elif [ "$TARGET_BRANCH" = "staging" ]; then
            ENVIRONMENT='staging'
          else
            ENVIRONMENT='dev'
          fi

          echo "Target environment is: $ENVIRONMENT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

  validate-parameters:
    needs: determine-environment
    environment:
      name: ${{needs.determine-environment.outputs.target_environment}}
    name: Validate SSM parameters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parameter checks
        uses: q4mobile/preflight-checks@feature/PRDVOPS-1121
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          target_aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          target_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          app_name: "platform-studio-eds"
          file_search_path: "./tests/studio-eds-ssm.tf"
