name: Pull Request Target POC
on: 
  pull_request_target:
    types:
      - opened

jobs:
  determine-environment:
    name: Determine the target environment
    runs-on: ubuntu-latest
    steps:
      - name: What branch are we merging into?
        shell: bash
        run: |
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}

          echo $TARGET_BRANCH

  print-variables:
    environment: prod # need to figure out how to determine this dynamically
    name: Print Variables
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_VARIABLE: ${{ vars.TEST_VARIABLE}}
    steps:
      - name: Print TEST_VARIABLE from target branch
        shell: bash
        run: |
          echo "TEST_VARIABLE: $TEST_VARIABLE"

