name: Pull Request Target POC
on: 
  pull_request:
    types:
      - opened

jobs:
  print-variables:
    name: Print Variables
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{vars.TEST_VARIABLE}}"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

